export default {
  id: "qwen-cloud",
  hidden: false,
  priority: 88,
  display: {
    name: "Qwen Cloud",
    icon: "cloud",
    color: "#6366F1",
    website: "https://home.qwencloud.com",
    notice: { signupUrl: "https://home.qwencloud.com" },
  },
  category: "free",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1/chat/completions",
    auth: { combined: true, header: "Authorization", scheme: "bearer" },
  },
  models: [
    { id: "qwen3.7-max", name: "Qwen3.7 Max" },
    { id: "qwen3.7-plus", name: "Qwen3.7 Plus" },
    { id: "qwen3.6-plus", name: "Qwen3.6 Plus" },
    { id: "qwen3.6-flash", name: "Qwen3.6 Flash" },
    { id: "qwen3.5-plus", name: "Qwen3.5 Plus" },
    { id: "qwen3.5-flash", name: "Qwen3.5 Flash" },
    { id: "qwen3-235b-a22b", name: "Qwen3 235B A22B" },
    { id: "qwen3-coder-plus", name: "Qwen3 Coder Plus" },
    { id: "qwen3-coder-flash", name: "Qwen3 Coder Flash" },
    { id: "qwen3-coder-next", name: "Qwen3 Coder Next" },
    { id: "qwen3-max", name: "Qwen3 Max" },
    { id: "qwen3-32b", name: "Qwen3 32B" },
    { id: "qwen3-14b", name: "Qwen3 14B" },
    { id: "qwen3-8b", name: "Qwen3 8B" },
    { id: "qwen-max", name: "Qwen Max" },
    { id: "qwen-plus", name: "Qwen Plus" },
    { id: "qwen-turbo", name: "Qwen Turbo" },
    { id: "qwen-flash", name: "Qwen Flash" },
    { id: "qwq-plus", name: "QwQ Plus" },
    { id: "qvq-max", name: "QvQ Max" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro (Qwen Cloud)" },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash (Qwen Cloud)" },
    { id: "deepseek-v3.2", name: "DeepSeek V3.2 (Qwen Cloud)" },
    { id: "glm-5.1", name: "GLM-5.1 (Qwen Cloud)" },
  ],
  features: {
    usage: false,
  },
};
